# Common properties for all micro services

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raviyasas/spring-clound-config-store
          search-paths:
           - '*service'