server:
  port: 8091

spring:
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: 1234

jsa:
  rabbitmq:
    exchange: jsa.direct
    routing-key: jsa.routingkey

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost